var input_array = [];
    
function get_para_2()
{

    for (var j = 1; j <= 6; j++) 
    {
        var input = document.getElementById("name_of_the_student_"+j).value;
        console.log(input);
        input_array.push(input);
    }
    document.getElementById("show_paragraph_2").innerHTML= input_array.join(" ");
    console.log(input_array);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
}
var input_2_array = [];
    
function get_para_1()
{

    for (var k = 1; k <= 6; k++) 
    {
        var input = document.getElementById("para_input_box_"+k).value;
        console.log(input);
        input_2_array.push(input);
    }
    document.getElementById("show_paragraph_1").innerHTML= input_2_array.join(" ");
    console.log(input_2_array);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
}